Repository mrstebo/FakerDotNet, pull requests merged in 2018-10, with the labels that each got.

#4 Feature/book faker
  README.md
  doc/book.md
  src/FakerDotNet/Data/BookData.cs
  src/FakerDotNet/Faker.cs
  src/FakerDotNet/FakerContainer.cs
  src/FakerDotNet/Fakers/BookFaker.cs
  tests/FakerDotNet.Tests/FakerContainerTests.cs
  tests/FakerDotNet.Tests/FakerTests.cs
  tests/FakerDotNet.Tests/Fakers/BookFakerTests.cs
Labels: enhancement

#7 Feature/time faker
  README.md
  doc/boolean.md
  doc/number.md
  doc/time.md
  src/FakerDotNet/Faker.cs
  src/FakerDotNet/FakerContainer.cs
  src/FakerDotNet/Fakers/TimeFaker.cs
  src/FakerDotNet/TimePeriod.cs
  tests/FakerDotNet.Tests/FakerContainerTests.cs
  tests/FakerDotNet.Tests/FakerTests.cs
  tests/FakerDotNet.Tests/Fakers/TimeFakerTests.cs
Labels: enhancement

#68 Added the Address faker
  README.md
  doc/address.md
  src/FakerDotNet/Data/AddressData.cs
  src/FakerDotNet/Faker.cs
  src/FakerDotNet/FakerContainer.cs
  src/FakerDotNet/Fakers/AddressFaker.cs
  src/FakerDotNet/Fakers/FakeFaker.cs
  tests/FakerDotNet.Tests/FakerContainerTests.cs
  tests/FakerDotNet.Tests/FakerTests.cs
  tests/FakerDotNet.Tests/Fakers/AddressFakerTests.cs
Labels: enhancement

#66 added friends faker and tests
  src/FakerDotNet/Data/FriendsData.cs
  src/FakerDotNet/Faker.cs
  src/FakerDotNet/FakerContainer.cs
  src/FakerDotNet/Fakers/FriendsFaker.cs
  tests/FakerDotNet.Tests/FakerContainerTests.cs
  tests/FakerDotNet.Tests/FakerTests.cs
  tests/FakerDotNet.Tests/Fakers/FriendsFakerTests.cs
Labels: enhancement

#73 Added the Lorem faker
  README.md
  doc/lorem.md
  doc/random.md
  src/FakerDotNet/Data/LoremData.cs
  src/FakerDotNet/Faker.cs
  src/FakerDotNet/FakerContainer.cs
  src/FakerDotNet/Fakers/LoremFaker.cs
  src/FakerDotNet/Fakers/RandomFaker.cs
  tests/FakerDotNet.Tests/FakerContainerTests.cs
  tests/FakerDotNet.Tests/FakerTests.cs
  tests/FakerDotNet.Tests/Fakers/LoremFakerTests.cs
  tests/FakerDotNet.Tests/Fakers/RandomFakerTests.cs
Labels: enhancement

#75 Made the data classes static.
  src/FakerDotNet/Data/AddressData.cs
  src/FakerDotNet/Data/AppData.cs
  src/FakerDotNet/Data/BookData.cs
  src/FakerDotNet/Data/FriendsData.cs
  src/FakerDotNet/Data/LoremData.cs
  src/FakerDotNet/Data/NameData.cs
  src/FakerDotNet/Data/PokemonData.cs
  src/FakerDotNet/Data/ZeldaData.cs
  src/FakerDotNet/Fakers/AddressFaker.cs
  src/FakerDotNet/Fakers/AppFaker.cs
  src/FakerDotNet/Fakers/BookFaker.cs
  src/FakerDotNet/Fakers/FriendsFaker.cs
  src/FakerDotNet/Fakers/NameFaker.cs
  src/FakerDotNet/Fakers/PokemonFaker.cs
  src/FakerDotNet/Fakers/ZeldaFaker.cs
  tests/FakerDotNet.Tests/Fakers/AddressFakerTests.cs
  tests/FakerDotNet.Tests/Fakers/AppFakerTests.cs
  tests/FakerDotNet.Tests/Fakers/BookFakerTests.cs
  tests/FakerDotNet.Tests/Fakers/FriendsFakerTests.cs
  tests/FakerDotNet.Tests/Fakers/NameFakerTests.cs
  tests/FakerDotNet.Tests/Fakers/PokemonFakerTests.cs
  tests/FakerDotNet.Tests/Fakers/ZeldaFakerTests.cs
Labels: refactor

#77 Using SetCulture attribute in some tests
  src/FakerDotNet/Fakers/AddressFaker.cs
  tests/FakerDotNet.Tests/Fakers/AddressFakerTests.cs
Labels: refactor

#85 Using pre-release GitVersion and removed the branch switch.
  appveyor.yml
Labels: invalid

#69 Added Beer faker data and tests. Tried to use _fakerContainer.Number …
  README.md
  doc/beer.md
  src/FakerDotNet/Data/BeerData.cs
  src/FakerDotNet/Faker.cs
  src/FakerDotNet/FakerContainer.cs
  src/FakerDotNet/Fakers/BeerFaker.cs
  tests/FakerDotNet.Tests/FakerContainerTests.cs
  tests/FakerDotNet.Tests/FakerTests.cs
  tests/FakerDotNet.Tests/Fakers/BeerFakerTests.cs
Labels: enhancement

#79 Game of Thrones Faker implementation
  README.md
  doc/gameofthrones.md
  src/FakerDotNet/Data/GameOfThronesData.cs
  src/FakerDotNet/Faker.cs
  src/FakerDotNet/FakerContainer.cs
  src/FakerDotNet/Fakers/GameOfThronesFaker.cs
  tests/FakerDotNet.Tests/Fakers/GameOfThronesFakerTests.cs
Labels: enhancement

#78 Added TeamFaker and underlying support
  README.md
  doc/team.md
  src/FakerDotNet/Data/TeamData.cs
  src/FakerDotNet/Faker.cs
  src/FakerDotNet/FakerContainer.cs
  src/FakerDotNet/Fakers/TeamFaker.cs
  tests/FakerDotNet.Tests/Fakers/TeamFakerTests.cs
Labels: enhancement

#80 Twin Peaks Faker implementation
  README.md
  doc/twin_peaks.md
  src/FakerDotNet/Data/TwinPeaksData.cs
  src/FakerDotNet/Faker.cs
  src/FakerDotNet/FakerContainer.cs
  src/FakerDotNet/Fakers/TwinPeaksFaker.cs
  tests/FakerDotNet.Tests/Fakers/TwinPeaksFakerTests.cs
Labels: enhancement

#81 Superhero Faker implementation
  README.md
  doc/superhero.md
  src/FakerDotNet/Data/SuperheroData.cs
  src/FakerDotNet/Faker.cs
  src/FakerDotNet/FakerContainer.cs
  src/FakerDotNet/Fakers/SuperheroFaker.cs
  tests/FakerDotNet.Tests/Fakers/SuperheroFakerTests.cs
Labels: enhancement

#86 Added the CompanyFaker
  README.md
  doc/company.md
  src/FakerDotNet/Algorithms/LuhnAlgorithm.cs
  src/FakerDotNet/Data/CompanyData.cs
  src/FakerDotNet/Extensions/StringCharactersExtension.cs
  src/FakerDotNet/Faker.cs
  src/FakerDotNet/FakerContainer.cs
  src/FakerDotNet/Fakers/CompanyFaker.cs
  tests/FakerDotNet.Tests/Algorithms/LuhnAlgorithmTests.cs
  tests/FakerDotNet.Tests/Extensions/StringCharactersExtensionTests.cs
  tests/FakerDotNet.Tests/FakerContainerTests.cs
  tests/FakerDotNet.Tests/FakerTests.cs
  tests/FakerDotNet.Tests/Fakers/CompanyFakerTests.cs
Labels: enhancement

#87 Added the ColorFaker
  README.md
  doc/color.md
  src/FakerDotNet/Data/ColorData.cs
  src/FakerDotNet/Faker.cs
  src/FakerDotNet/FakerContainer.cs
  src/FakerDotNet/Fakers/ColorFaker.cs
  tests/FakerDotNet.Tests/FakerContainerTests.cs
  tests/FakerDotNet.Tests/FakerTests.cs
  tests/FakerDotNet.Tests/Fakers/ColorFakerTests.cs
Labels: enhancement

#63 Add the RickAndMorty faker
  README.md
  doc/rick_and_morty.md
  src/FakerDotNet/Data/RickAndMortyData.cs
  src/FakerDotNet/Faker.cs
  src/FakerDotNet/FakerContainer.cs
  src/FakerDotNet/Fakers/RickAndMortyFaker.cs
  tests/FakerDotNet.Tests/FakerContainerTests.cs
  tests/FakerDotNet.Tests/FakerTests.cs
  tests/FakerDotNet.Tests/Fakers/RickAndMortyFakerTests.cs
Labels: enhancement

#88 Vehicle faker
  README.md
  doc/vehicle.md
  src/FakerDotNet/Checksums/VehicleVinChecksum.cs
  src/FakerDotNet/Data/VehicleData.cs
  src/FakerDotNet/Faker.cs
  src/FakerDotNet/FakerContainer.cs
  src/FakerDotNet/Fakers/VehicleFaker.cs
  tests/FakerDotNet.Tests/Algorithms/VinCheckSumTests.cs
  tests/FakerDotNet.Tests/FakerContainerTests.cs
  tests/FakerDotNet.Tests/FakerTests.cs
  tests/FakerDotNet.Tests/Fakers/RandomFakerTests.cs
  tests/FakerDotNet.Tests/Fakers/VehicleFakerTests.cs
Labels: enhancement

#90 Add the University faker
  README.md
  doc/university.md
  src/FakerDotNet/Data/UniversityData.cs
  src/FakerDotNet/Faker.cs
  src/FakerDotNet/FakerContainer.cs
  src/FakerDotNet/Fakers/UniversityFaker.cs
  tests/FakerDotNet.Tests/FakerContainerTests.cs
  tests/FakerDotNet.Tests/FakerTests.cs
  tests/FakerDotNet.Tests/Fakers/UniversityFakerTests.cs
Labels: enhancement
